"""One-command runner for local evaluation, prediction, validation, and zipping.

This script is intentionally standard-library only. It makes the hackathon
workflow easy to repeat without changing the canonical entry points:

- production agent: code/main.py
- evaluator: code/evaluation/main.py
- final predictions: output.csv
"""

from __future__ import annotations

import argparse
import asyncio
import csv
import shutil
import sys
import zipfile
from pathlib import Path
from typing import Iterable, Sequence

from main import OUTPUT_COLUMNS, process_dataset


REPO_ROOT = Path(__file__).resolve().parents[1]
CODE_ROOT = REPO_ROOT / "code"
ROOT_REPORT = REPO_ROOT / "evaluation" / "evaluation_report.md"
CODE_REPORT = CODE_ROOT / "evaluation" / "evaluation_report.md"


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    """Read a CSV file into rows."""
    with path.open("r", encoding="utf-8", newline="") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def validate_output(claims_csv: Path, output_csv: Path) -> tuple[bool, list[str]]:
    """Validate output row count, required schema, and empty required cells."""
    problems: list[str] = []
    if not claims_csv.exists():
        problems.append(f"Missing input claims file: {claims_csv}")
        return False, problems
    if not output_csv.exists():
        problems.append(f"Missing output file: {output_csv}")
        return False, problems

    claims = read_csv_rows(claims_csv)
    with output_csv.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
        fields = reader.fieldnames or []

    if fields != OUTPUT_COLUMNS:
        problems.append("Output columns do not match problem_statement.md exactly.")
    if len(rows) != len(claims):
        problems.append(f"Output row count {len(rows)} does not match claims row count {len(claims)}.")
    empty_cells = sum(1 for row in rows for column in OUTPUT_COLUMNS if row.get(column, "") == "")
    if empty_cells:
        problems.append(f"Output contains {empty_cells} empty required cells.")
    return not problems, problems


def mirror_report() -> None:
    """Keep the operational report inside code/evaluation for code.zip."""
    if ROOT_REPORT.exists():
        CODE_REPORT.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ROOT_REPORT, CODE_REPORT)


def iter_zip_files() -> Iterable[Path]:
    """Yield submission files while excluding caches and generated bytecode."""
    include_roots = [CODE_ROOT, REPO_ROOT / "evaluation"]
    for root in include_roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.is_dir():
                continue
            parts = set(path.parts)
            if "__pycache__" in parts or ".cache" in parts:
                continue
            if path.suffix in {".pyc", ".pyo"}:
                continue
            yield path


def make_code_zip(zip_path: Path) -> None:
    """Create a code.zip containing runnable code and evaluation assets."""
    mirror_report()
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(iter_zip_files()):
            archive.write(path, path.relative_to(REPO_ROOT))


async def run_workflow(args: argparse.Namespace) -> int:
    """Run evaluation, predictions, validation, and optional packaging."""
    mirror_report()

    if not args.skip_evaluation:
        from evaluation.main import evaluate

        print("Running sample evaluation...")
        await evaluate(REPO_ROOT / "dataset" / "sample_claims.csv", None)

    print("\nGenerating final predictions...")
    predictions = await process_dataset(
        input_csv=args.input,
        output_csv=args.output,
        use_vlm=args.use_vlm,
        concurrency=args.concurrency,
        model=args.model,
    )
    print(f"Wrote {len(predictions)} prediction rows to {args.output}")

    ok, problems = validate_output(args.input, args.output)
    if ok:
        print("Validation passed: row count, schema, and required cells are submission-ready.")
    else:
        print("Validation failed:")
        for problem in problems:
            print(f"- {problem}")
        return 1

    if args.make_zip:
        make_code_zip(args.zip_path)
        print(f"Created code package: {args.zip_path}")
    return 0


def parse_args(argv: Sequence[str] | None = None) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description="Run the full Orchestrate submission workflow.")
    parser.add_argument("--input", type=Path, default=REPO_ROOT / "dataset" / "claims.csv")
    parser.add_argument("--output", type=Path, default=REPO_ROOT / "output.csv")
    parser.add_argument("--use-vlm", choices=["auto", "always", "never"], default="auto")
    parser.add_argument("--concurrency", type=int, default=20)
    parser.add_argument("--model", default="gpt-4o")
    parser.add_argument("--skip-evaluation", action="store_true")
    parser.add_argument("--make-zip", action="store_true")
    parser.add_argument("--zip-path", type=Path, default=REPO_ROOT / "code.zip")
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry point."""
    args = parse_args(argv)
    return asyncio.run(run_workflow(args))


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
